### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by isapir** [cfmleditor/cfmleditor#14]
When I run `npm run build` I get errors.  Is that a wrong target version?  How do I fix it?

```
❯ npm run build

> cfmleditor@0.6.18 build
> tsc -p ./

/workspace/oss/cfmleditor/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/oss/cfmleditor/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Running `npm run rebuild` throws a different error:

```
❯ npm run rebuild

> cfmleditor@0.6.18 rebuild
> npm run clean && npm run build


> cfmleditor@0.6.18 clean
> rimraf out *.vsix

file:///workspace/oss/cfmleditor/node_modules/rimraf/dist/esm/bin.mjs:6
const { version } = JSON.parse(await readFile(pjDist, 'utf8').catch(() => readFile(pj, 'utf8')));
                               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by ghedwards** [comment]
Strange, this appears to be failing due to node_modules any eslint rules should exclude the node_modules directories, I'll take a look when I get a moment.

**Comment by ghedwards** [comment]
Apparently it might be an environment thing, but I've also added the .eslintignore file https://stackoverflow.com/questions/60192096/eslint-not-ignoring-node-modules-folder, let me know if this doesn't fix it.

**Comment by isapir** [comment]
Still the same error. You can see from the git log command at the end that I have the latest patch:

```
❯ git pull
Updating 024decc..095e8e1
Fast-forward
 .eslintignore | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 .eslintignore
❯ npm run build

> cfmleditor@0.6.18 build
> tsc -p ./

/workspace/oss/cfmleditor/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/oss/cfmleditor/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
❯ npm run rebuild

> cfmleditor@0.6.18 rebuild
> npm run clean && npm run build


> cfmleditor@0.6.18 clean
> rimraf out *.vsix

file:///workspace/oss/cfmleditor/node_modules/rimraf/dist/esm/bin.mjs:6
const { version } = JSON.parse(await readFile(pjDist, 'utf8').catch(() => readFile(pj, 'utf8')));
                               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
❯ git log --oneline -7
      1 095e8e1 (HEAD -> master, origin/master, origin/HEAD) Create .eslintignore
      2 024decc 0.6.18
      3 91a48c5 Merge pull request #12 from cfmleditor/multi-cursor-auto-close-fix
      4 d4e151a (origin/multi-cursor-auto-close-fix) Multi line autoclose fixes
      5 e2d3852 Merge pull request #11 from sfeldkamp/multi-cursor-auto-close-fix
      6 2feb235 Merge branch 'multi-cursor-auto-close-fix' into multi-cursor-auto-close-fix
      7 07b5396 0.6.17
```

**Comment by ghedwards** [comment]
Check your NPM / Node version as per that stackoverflow link

**Comment by isapir** [comment]
You are right.  Somehow I had an older (v12) version of node installed in `/usr/bin/node` which took precedence over the version I installed elsewhere.  I deleted `/usr/bin/node` and it worked.

Thanks!
