### ISSUE TITLE
 ERR [Extension Host] TypeError: Cannot create property '$' on number '1'

### ISSUE THREAD

**Issue by ivanionut** [cfmleditor/cfmleditor#5]
hi @garethedwards-tass ,
I'm getting this error in console (vscode) and autocomplete doesn't work:

```
 ERR [Extension Host] TypeError: Cannot create property '$' on number '1'
    at append (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/append.js:28:37)
    at reducer (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/index.js:44:33)
    at Array.reduce (<anonymous>)
    at Object.addWord (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/index.js:48:13)
    at setUserFunction (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:259:26)
    at /Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:338:9
    at ComponentFunctions.forEach (<anonymous>)
    at cacheComponent (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:337:25)
    at cacheComponentFromDocument (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:440:5)
    at /Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:414:17
console.ts:137 [Extension Host] TypeError: Cannot create property '$' on number '1'
    at append (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/append.js:28:37)
    at reducer (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/index.js:44:33)
    at Array.reduce (<anonymous>)
    at Object.addWord (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/node_modules/trie-prefix-tree/dist/index.js:48:13)
    at setUserFunction (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:259:26)
    at /Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:338:9
    at ComponentFunctions.forEach (<anonymous>)
    at cacheComponent (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:337:25)
    at cacheComponentFromDocument (/Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:440:5)
    at /Users/ivan/.vscode-insiders/extensions/cfmleditor.cfmleditor-0.6.12/out/features/cachedEntities.js:414:17 (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:57439))
p @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
x.onmessage @ localProcessExtensionHost.ts:376
log.ts:437   ERR [Extension Host] Unable to add $ to trie
console.ts:137 [Extension Host] Unable to add $ to trie (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:57439))
```

**Comment by ghedwards** [comment]
@ivanionut do you use $ characters in your function or component names ?

**Comment by ghedwards** [comment]
I could try strip out the $ character from the function or component name, but I'm not sure if you're actively using these characters, let me know.

**Comment by ghedwards** [comment]
Wouldn't just be the file you're working in, any CFC / functions in your workspace

**Comment by ghedwards** [comment]
The lines failing is due to a 3rd party library that indexes function names, and it doesn't like $ symbols

**Comment by ghedwards** [comment]
Thanks, that helps a lot, I'll look into it and let you know

**Comment by ghedwards** [comment]
@ivanionut grab / install https://github.com/cfmleditor/cfmleditor/blob/3615b17e80f02ab47e9c068da462b4dbf5a821f7/cfmleditor-0.6.14.vsix and let me know how it goes?

**Comment by ghedwards** [comment]
Comments and edge cases for parsing is the biggest issue with the plugin, if there is any further info about the file or the text it's failing on let me know, in the mean time I can try strip out the $ character and we can try test that

**Comment by ghedwards** [comment]
I am working on a cfml tree sitter parser, but it's very early days and I'm not confident it'll ever get to a production state

**Comment by ghedwards** [comment]
I think fault tolerance is important too, so I'll consider what I can do to make things not fail so badly when something goes wrong

**Comment by ghedwards** [comment]
@ivanionut no promises, but some improvements in the latest vsix https://github.com/cfmleditor/cfmleditor/blob/master/cfmleditor-0.6.14.vsix
